//! Loot economy (CHUNK C11).
//!
//! Vendor prices come from `assets/data/prices.json` (generated by
//! `scripts/gen_prices.py` from bestiary drop rarity + act tier). The
//! innkeeper buys anything priced at 80% and sells staples at 120%; the
//! auction house is seeded with NPC listings at boot and daily so a lone
//! player still sees a market, and takes a 5% cut as a gold sink.

use std::collections::BTreeMap;
use std::sync::OnceLock;

fn prices() -> &'static BTreeMap<String, u32> {
    static PRICES: OnceLock<BTreeMap<String, u32>> = OnceLock::new();
    PRICES.get_or_init(|| {
        serde_json::from_str(include_str!("../../../assets/data/prices.json"))
            .expect("prices.json parses")
    })
}

/// Table price of an item, if the economy knows it.
pub fn vendor_price(item: &str) -> Option<u32> {
    prices().get(item).copied()
}

/// What the innkeeper pays when buying from a player (80% of table).
pub fn sell_price(item: &str) -> Option<u32> {
    vendor_price(item).map(|p| (p * 4 / 5).max(1))
}

/// Staples the innkeeper sells (at 120% of table).
pub const STAPLES: &[&str] = &["bread", "fruit", "healing_potion", "taming_lasso", "stone_axe"];

pub fn staple_price(item: &str) -> Option<u32> {
    STAPLES
        .contains(&item)
        .then(|| vendor_price(item).map(|p| (p * 6 / 5).max(1)))
        .flatten()
}

/// The auction house keeps 5% of every sale (gold sink).
pub fn ah_cut(price: u32) -> u32 {
    price - price * 5 / 100
}

/// NPC seller names for seeded listings — Sumerian King List.
pub const NPC_SELLERS: &[&str] = &[
    "Alulim", "Alalngar", "Enmenluana", "Enmengalana", "Dumuzid",
    "Ensipadzidana", "Enmeduranki", "Ubara-Tutu",
];

/// Act-appropriate seed stock (item pool for NPC listings).
pub const SEED_STOCK: &[&str] = &[
    "healing_potion", "taming_lasso", "bronze_sword", "hide_vest",
    "thick_hide", "orichalcum_ore", "bread", "fruit",
];

/// Deterministic-enough pick without rand: hash a counter.
fn mix(seed: u64) -> u64 {
    let mut x = seed.wrapping_mul(0x9E37_79B9_7F4A_7C15);
    x ^= x >> 30;
    x = x.wrapping_mul(0xBF58_476D_1CE4_E5B9);
    x ^ (x >> 27)
}

/// One seeded listing: (seller, item, price at 90–140% of table).
pub fn seed_listing(n: u64) -> (&'static str, &'static str, u32) {
    let seller = NPC_SELLERS[(mix(n) % NPC_SELLERS.len() as u64) as usize];
    let item = SEED_STOCK[(mix(n + 101) % SEED_STOCK.len() as u64) as usize];
    let table = vendor_price(item).unwrap_or(10);
    let pct = 90 + (mix(n + 202) % 51) as u32; // 90..=140
    (seller, item, (table * pct / 100).max(1))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn price_table_loads_and_sells_at_80pct() {
        assert_eq!(vendor_price("bread"), Some(2));
        let hp = vendor_price("healing_potion").unwrap();
        assert_eq!(sell_price("healing_potion"), Some(hp * 4 / 5));
        assert_eq!(sell_price("no_such_item"), None);
        // Every price is positive and staples resolve at 120%.
        assert!(prices().values().all(|p| *p > 0));
        assert_eq!(staple_price("healing_potion"), Some(hp * 6 / 5));
        assert_eq!(staple_price("orichalcum_blade"), None, "not a staple");
    }

    #[test]
    fn ah_cut_is_5pct() {
        assert_eq!(ah_cut(100), 95);
        assert_eq!(ah_cut(20), 19);
    }

    #[test]
    fn seed_listings_are_valid() {
        for n in 0..50 {
            let (seller, item, price) = seed_listing(n);
            assert!(NPC_SELLERS.contains(&seller));
            let table = vendor_price(item).unwrap();
            assert!(price >= (table * 90 / 100).max(1) && price <= table * 140 / 100);
        }
    }
}
