//! Bestiary integration (CHUNK C03).
//!
//! `assets/data/mobs.json` (generated by `scripts/gen_mobs.py` from the
//! 2,500-entry markdown bestiary) is compiled into the binary so the server
//! works from any cwd (including the .app bundle). Each act spawns a mix of
//! bestiary species from its habitat + level band alongside the legacy
//! quest-critical tags.

use antediluvia_protocol::Act;
use std::collections::HashMap;
use std::sync::OnceLock;

#[derive(serde::Deserialize)]
pub struct MobDef {
    pub id: u32,
    pub name: String,
    pub tag: String,
    pub level_min: u32,
    pub level_max: u32,
    pub act: String,
    pub temperament: String,
    pub tameable: bool,
    #[serde(default)]
    pub mount: Option<String>,
    pub drops: Vec<String>,
}

impl MobDef {
    /// Aggressive/bloodthirsty/territorial spawn as enemies; docile and
    /// skittish species graze as neutral wildlife.
    pub fn hostile(&self) -> bool {
        matches!(self.temperament.as_str(), "aggressive" | "bloodthirsty" | "territorial")
    }

    pub fn mid_level(&self) -> u32 {
        (self.level_min + self.level_max) / 2
    }
}

static MOBS: OnceLock<Vec<MobDef>> = OnceLock::new();
static BY_TAG: OnceLock<HashMap<&'static str, &'static MobDef>> = OnceLock::new();

/// Legacy spawn-table / quest / wildlife / resource tags. A few bestiary
/// names snake_case onto these ("serpent", "leviathan") — the legacy tags
/// win, so the original quest mobs keep their stats and drops.
const RESERVED_TAGS: &[&str] = &[
    "serpent", "watcher", "giant", "shade", "leviathan", "cainite", "elemental",
    "ember_wisp", "cultist", "chasm_fiend", "caravan_wagon", "oathstone",
    "stargazer", "blood_drinker", "weapon_cache", "citadel_guard",
    "furnace_regulator", "enchanter_smith", "sorcerer", "geyser",
    "nephilim_raider", "drowned_beast", "scroll_crate", "dire_wolf", "swift_claw",
    "deer", "goat", "boar", "dog", "fox", "tree", "rock", "questgiver",
];

pub fn all_mobs() -> &'static [MobDef] {
    MOBS.get_or_init(|| {
        serde_json::from_str(include_str!("../../../assets/data/mobs.json"))
            .expect("mobs.json parses")
    })
}

pub fn mob_by_tag(tag: &str) -> Option<&'static MobDef> {
    if RESERVED_TAGS.contains(&tag) || tag.ends_with("_alpha") {
        return None; // legacy mobs and act bosses are never bestiary lookups
    }
    BY_TAG
        .get_or_init(|| all_mobs().iter().map(|m| (m.tag.as_str(), m)).collect())
        .get(tag)
        .copied()
}

/// The act's nominal level band (used to pick level-appropriate species).
pub fn act_band(act: Act) -> (u32, u32) {
    match act {
        Act::Eden => (1, 12),
        Act::Hermon => (13, 24),
        Act::Nephilim => (25, 36),
        Act::Enoch => (37, 48),
        Act::Flood => (49, 60),
    }
}

/// Species eligible to spawn in an act: right habitat, level range
/// overlapping the act band — widened until at least 10 qualify.
pub fn species_for_act(act: Act) -> Vec<&'static MobDef> {
    let key = act.as_str();
    let (lo, hi) = act_band(act);
    let mut widen = 0u32;
    loop {
        let (lo, hi) = (lo.saturating_sub(widen), hi + widen);
        let picks: Vec<_> = all_mobs()
            .iter()
            .filter(|m| m.act == key && m.level_max >= lo && m.level_min <= hi)
            .filter(|m| mob_by_tag(&m.tag).is_some()) // skip reserved-tag collisions
            .collect();
        if picks.len() >= 10 || widen >= 60 {
            return picks;
        }
        widen += 6;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bestiary_loads_all_entries() {
        assert_eq!(all_mobs().len(), 2500);
        // Spot-checks against the markdown source (Vol 01).
        // (tags repeat across volumes — spot-check by bestiary ID)
        let m = all_mobs().iter().find(|m| m.id == 3).expect("ID-0003");
        assert_eq!((m.level_min, m.level_max), (32, 34));
        assert_eq!(m.act, "hermon");
        assert!(m.hostile());
        assert!(m.drops.contains(&"iron_scales".to_string()));
        let m = all_mobs().iter().find(|m| m.id == 1).expect("ID-0001");
        assert_eq!(m.act, "flood");
        assert!(!m.hostile(), "docile species are not hostile");
        assert!(!m.tameable);
        assert!(mob_by_tag("starving_smilodon").is_some());
    }

    #[test]
    fn every_act_has_enough_species() {
        for act in Act::ALL {
            let s = species_for_act(act);
            assert!(s.len() >= 10, "{act:?}: only {} species", s.len());
        }
    }
}
